<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\StudyPlanner.Domain\StudyPlanner.Domain.csproj" />
    <ProjectReference Include="..\StudyPlanner.Deadlines\StudyPlanner.Deadlines.csproj" />
  </ItemGroup>
</Project>
