<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\StudyPlanner.Domain\StudyPlanner.Domain.csproj" />
    <ProjectReference Include="..\StudyPlanner.Application\StudyPlanner.Application.csproj" />
  </ItemGroup>
</Project>
